informasi/urls.py
from django.urls import path
from .views import InformasiSDMView, VideoTutorialView, pdf_view, pdf_list, pdf_viewer, InformasiListView, InformasiDetailView, DeleteInformasiView


urlpatterns = [
    path('', InformasiListView.as_view(), name='informasi_view'),
    path('add/', InformasiSDMView.as_view(), name='add_informasi_view'),
    path('<str:slug>/', InformasiDetailView.as_view(), name='informasi_view'),
    path('<int:pk>/delete/', DeleteInformasiView.as_view(), name='delete_informasi_view'),
    path('add/<int:id>/', InformasiSDMView.as_view(), name='informasi_update_view'),
    path('pdfs/', pdf_list, name='pdf_list'),
    path('pdf/<int:id>/', pdf_view, name='pdf_view'),#get pdf from file saved and view pdf to template
    path('pdf-viewer/', pdf_viewer, name='pdf_viewer'),#generate instance pdf and view pdf to template
    path('video/', VideoTutorialView.as_view(), name='tutorial_view'),
    path('video/<int:id>/', VideoTutorialView.as_view(), name='tutorial_view'), 
]

lapor/urls.py
from django.urls import path
from .views import LaporanView, UpdateLaporanView, SaranView, UpdateSaranView


urlpatterns = [
    path('', LaporanView.as_view(), name='laporan_view'),
    path('<int:id>/', UpdateLaporanView.as_view(), name='laporan_update_view'),
    path('saran/', SaranView.as_view(), name='saran_view'),
    path('saran/<int:id>/', UpdateSaranView.as_view(), name='saran_update_view'),
]

myaccount/urls.py
from django.urls import path

from .views import (
    logout_view, 
    SimaduLoginView, 
    ChangePassword, 
    ChangePasswordDone, 
    ProfilListView, 
    ProfilDetailView, 
    ProfilUpdateView, 
    ProfilCreateView,
    PegawaiAutocompleteView
)


urlpatterns=[
    path('login/', SimaduLoginView.as_view(), name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('ganti-password/', ChangePassword.as_view(), name='ganti_password_view'),
    path('ganti-password/done/', ChangePasswordDone.as_view(), name='ganti_password_done_view'),
    path('profil/', ProfilListView.as_view(), name='profil_view'),
    path('profil/add/', ProfilCreateView.as_view(), name='profil_create_view'),
    path('profil/detail/<int:pk>/', ProfilDetailView.as_view(), name='profil_detail_view'),
    path('profil/<int:pk>/update/', ProfilUpdateView.as_view(), name='profil_update_view'),
    path('ajax-pegawai-autocomplete/', PegawaiAutocompleteView.as_view(), name='ajax_pegawai_autocomplete')
]

sisdm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('myaccount.urls', 'myaccount_urls'), namespace='myaccount_urls')),
    path('riwayat/', include(('dokumen.urls', 'riwayat_urls'), namespace='riwayat_urls')),
    path('layanan/', include(('layanan.urls', 'layanan_urls'), namespace='layanan_urls')),
    path('struktur/', include(('strukturorg.urls', 'struktur_urls'), namespace='struktur_urls')),
    path('sdm/', include(('jenissdm.urls', 'sdm_urls'), namespace='sdm_urls')),
    path('file/', include(('file_dokumen.urls', 'file_urls'), namespace='file_urls')),
    path('', include(('dashboard.urls', 'dashboard_urls'), namespace='dashboard_urls')),
    path('informasi/', include(('informasi.urls', 'informasi_urls'), namespace='informasi_urls')),
    path('disiplin/', include(('disiplinsdm.urls', 'disiplinsdm_urls'), namespace='disiplinsdm_urls')),
    path('laporan/', include(('lapor.urls', 'laporan_urls'), namespace='laporan_urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informasi/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from hitcount.models import HitCount, HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from datetime import datetime
from pytz import timezone as tz
from tinymce.models import HTMLField
# Create your models here.


class KategoriInformasi(models.Model):
    kategori = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.kategori

@receiver(pre_save, sender=KategoriInformasi)
def slugify_kategori_informasi(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.kategori)

STATUS = (
    ('draft', 'draft'),
    ('publish', 'publish')
)

class InformasiSDM(models.Model, HitCountMixin):
    kategori = models.ForeignKey(KategoriInformasi, on_delete=models.CASCADE)
    author = models.ForeignKey('myaccount.Users', on_delete=models.SET_NULL, null=True)
    judul = models.CharField(max_length=250)
    isi = HTMLField(blank=True)
    gambar = models.ImageField(upload_to='informasi/gambar/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS, default='draft') 
    headline = models.BooleanField(default=False)
    active = models.BooleanField(default=True)#menentukan apakah dokumen dapat diakses oleh user atau hanya sebagai arsip
    pdf_file = models.FileField(upload_to='informasi/file/', blank=True, null=True)
    slug = models.SlugField(blank=True, max_length=250) #slug untuk judul
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.judul
    
    
@receiver(pre_save, sender=InformasiSDM)
def slugify_informasi(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.judul)


class KategoriVideo(models.Model):
    kategori = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.kategori

@receiver(pre_save, sender=KategoriVideo)
def slugify_kategori_video(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.kategori)


class VideoYoutube(models.Model):
    kategori = models.ForeignKey(KategoriVideo, on_delete=models.CASCADE)
    author = models.ForeignKey('myaccount.Users', on_delete=models.SET_NULL, null=True)
    judul_video = models.CharField(max_length=250, blank=True)
    id_video = models.CharField(max_length=200, unique=True)
    status = models.CharField(max_length=20, choices=STATUS, default='draft')
    headline = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, max_length=250) #slug untuk judul
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.judul_video

    
@receiver(pre_save, sender=VideoYoutube)
def slugify_judul_video(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.judul_video)


class VideoComment(models.Model):
    video = models.ForeignKey(VideoYoutube, on_delete=models.CASCADE)
    author = models.ForeignKey('myaccount.Users', on_delete=models.SET_NULL, null=True)
    comment = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment


class ReVideoComment(models.Model):
    comment = models.ForeignKey(VideoComment, on_delete=models.CASCADE)
    author = models.ForeignKey('myaccount.Users', on_delete=models.SET_NULL, null=True)
    recomment = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.recomment


class NasehatdanHadist(models.Model):
    hadist = models.TextField()
    author_perawi = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.hadist

informasi/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from .models import VideoComment, ReVideoComment, VideoYoutube, InformasiSDM


class TinyMCEWidget(TinyMCE): 
	def use_required_attribute(self, *args): 
		return False


class InformasiSDMForm(forms.ModelForm): 
    judul = forms.CharField(max_length=250)
    isi = forms.CharField(widget=TinyMCEWidget(attrs={'required': False, 'cols': 30, 'rows': 10}))
    class Meta: 
        model = InformasiSDM
        fields = ('kategori', 'author', 'judul', 'isi', 'gambar', 'status', 'headline', 'active', 'pdf_file')
         


class VideoYoutubeForm(forms.ModelForm):
    class Meta:
        model = VideoYoutube
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.request=kwargs.pop("request", None)
        super(VideoYoutubeForm, self).__init__(*args, **kwargs)
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['slug'].widget = forms.HiddenInput()


class VideoCommentForm(forms.ModelForm):
    class Meta:
        model = VideoComment
        fields = ('video', 'author', 'comment')

    def __init__(self, *args, **kwargs):
        self.request=kwargs.pop("request", None)
        super(VideoCommentForm, self).__init__(*args, **kwargs)
        self.fields['video'].widget = forms.HiddenInput()
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['comment'].label = ''
        self.fields['comment'].widget.attrs.update({'cols': 80, 'rows': 3})


class ReVideoCommentForm(forms.ModelForm):
    class Meta:
        model = ReVideoComment
        fields = ('comment', 'author', 'recomment')

    def __init__(self, *args, **kwargs):
        self.request=kwargs.pop("request", None)
        super(ReVideoCommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget = forms.HiddenInput()
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['recomment'].label = ''

informasi/templates/videotemplate/video.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title_page %}

{% endblock title_page %}

{% block styles %}
<link rel="stylesheet" href="{% static 'dist/css/informasi.css' %}">
{% endblock styles %}

{% block content %}
<div class="container">
    {% if video %}
        {% if request.user.is_superuser %}
            <a href="{% url 'informasi_urls:tutorial_view' %}#openModal" class="btn btn-info" >Tambah Video</a>
        {% endif %}
        <div class="row">
            <div class="col-md-7 mb-5 mr-3">
                <!-- Main video -->
                <div class="row">
                    <div class=" col-md-12 auto-resizable-iframe">
                        <div>
                            <iframe id="mainVideo" src="https://www.youtube.com/embed/{{video.id_video}}" frameborder="0" class="rounded" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen ></iframe>
                            <h3>{{video.judul_video}}</h3>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                            <div class="image">
                                {% if video.author.profil_user.foto %}
                                <img src="{{video.author.profil_user.foto.url}}" class="img-circle elevation-2" alt="User Image">
                                {% else %}
                                <img src="{% static 'dist/img/avatar5.png' %}" class="img-circle elevation-2" alt="User Image">
                                {% endif %}
                            </div>
                            <div class="info">
                                <a href="{% url 'myaccount_urls:profil_view' %}" class="d-block">{{video.author.first_name}} {{video.author.last_name}}</a>
                                <span>{{video.created_at|naturaltime}}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{commentform | crispy}}
                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Simpan" class="btn btn-success">
                            </div>
                        </form>
                    </div>
                    <div class="mb-5 col-md-12" style="box-sizing: border-box;">
                        <h5>{{video.videocomment_set.all|length}} Komentar</h5>
                        <div class="col-md-12 d-flex justify-content-center">
                            <hr style="width:100%; height: 1px; border:0; background: linear-gradient(to right, #171717, #afaeae);">
                        </div>
                        {% if video.videocomment_set.all %}
                        {% for item in video.videocomment_set.all %}
                        <div class="col-md-12" style="width: 100%;">
                            <div class="pb-3 d-flex justify-content-start">
                                <div class="image">
                                    {% if item.author.profil_user.foto %}
                                    <img width="50" src="{{item.author.profil_user.foto.url}}" class="img-circle elevation-2 mr-3" alt="User Image">
                                    {% else %}
                                    <img src="{% static 'dist/img/avatar5.png' %}" class="img-circle elevation-2" alt="User Image">
                                    {% endif %}
                                </div>
                                <div class="row info">
                                    <a style="text-decoration: none;" href="#" class="d-block mr-2">{{item.author.first_name}} {{item.author.last_name}}</a>
                                    <span style="font-size: small; color:#424141">{{item.created_at|naturaltime}}</span>
                                    <div class="col-md-12">
                                        <p>{{item.comment}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="col-md-12">
                            <h5>Belum ada komentar saat ini..</h5>
                        </div>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <!-- List of related videos -->
                <div class="row">
                    <div class="col-md-12" id="kategorivideo">
                        <h4>Kategori Video</h4>
                        <ul style="display: flex; flex-direction:column; gap:5px;">
                            {% for item in kategori %}
                            <a href="{% url 'informasi_urls:tutorial_view' %}?kategori={{item.slug}}">
                                <li class="list">{{item.kategori}}</li>
                            </a>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-md-12">
                        {% for item in data %}
                        <div class="image-container">
                            <a href="{% url 'informasi_urls:tutorial_view' %}?vid={{item.id_video}}" id="get_videoid">
                                <div class="d-flex justify-content-start mt-2">
                                    <!-- <input type="hidden" name="id_video" id="video_input_id" value="{{item.id_video}}"> -->
                                    <div class="mr-2">
                                        <img src="https://img.youtube.com/vi/{{item.id_video}}/default.jpg" alt="Play Video" style="cursor: pointer;">
                                    </div>
                                    <div style="color: black;">
                                        {{item.judul_video}}
                                        <br><span style="font-size: small; color:#424141">{{item.created_at|naturaltime}}</span>
                                    </div>
                                </div>
                            </a>
                            {% if request.user.is_superuser %}
                            <a href="{% url 'informasi_urls:tutorial_view' id=item.id %}?vid={{item.id_video}}#openModal" class="btn btn-outline-info edit-button"><i class="fas fa-edit" ></i></a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            <h4>Belum ada video diupload</h4>
        </div>
    </div>
    
    {% endif %}
</div>

<!-- modal untuk persetujuan cuti -->
<div id="openModal" class="modalinfo">
    <div class="modal-content">
        <a href="#close" title="Close" class="close">&times;</a>
        {% if get_id %}
            <h4>Edit Video</h4>
        {% else %}
            <h4>Tambah Video</h4>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Simpan" class="btn btn-success mt-3">
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    function toggleForm() {
        var form = document.getElementById("addVideoForm");
        if (form.style.display === "none") {
          form.style.display = "block";
        } else {
          form.style.display = "none";
        }
      }
      
</script>


{% endblock script %}