dokumen/urls.py
from django.urls import path

from .views import (
    RiwayatHomeView,
    UrutkanRiwayatPendidikanView,
    RiwayatPendidikanView,
    RiwayatPendidikanUpdateView,
    RiwayatPendidikanDeleteView,
    RiwayatPanggolView,
    RiwayatPanggolUpdateView,
    UrutkanRiwayatPanggolView,
    RiwayatPanggolDeleteView,
    RiwayatPengangkatanView,
    RiwayatPengangkatanUpdateView,
    UrutkanRiwayatPengangkatanView,
    RiwayatPengangkatanDeleteView,
    RiwayatJabatanView,
    RiwayatJabatanUpdateView,
    UrutkanRiwayatJabatanView,
    RiwayatJabatanDeleteView,
    RiwayatPenempatanView,
    RiwayatPenempatanInstansiBeforeCreateView,
    RiwayatPenempatanInstansiBeforUpdateView,
    # RiwayatPenempatanUpdateView,
    UrutkanRiwayatPenempatanView,
    RiwayatPenempatanDeleteView,
    RiwayatGajiBerkalaView,
    RiwayatGajiBerkalaUpdateView,
    UrutkanRiwayatGajiBerkalaView,
    RiwayatGajiBerkalaDeleteView,
    RiwayatKinerjaView,
    RiwayatKinerjaUpdateView,
    UrutkanRiwayatKinerjaView,
    RiwayatKinerjaDeleteView,
    RiwayatPenghargaanView,
    RiwayatPenghargaanUpdateView,
    UrutkanRiwayatPenghargaanView,
    RiwayatPenghargaanDeleteView,
    RiwayatHukumanView,
    RiwayatHukumanUpdateView,
    UrutkanRiwayatHukumanView,
    RiwayatHukumanDeleteView,
    RiwayatCutiView,
    RiwayatCutiUpdateView,
    UrutkanRiwayatCutiView,
    RiwayatDiklatListView,
    RiwayatDiklatDetailView,
    RiwayatDiklatCreateView,
    RiwayatDiklatView,
    RiwayatDiklatPegawaiView,
    RiwayatDiklatUpdateView,
    UrutkanRiwayatDiklatView,
    RiwayatDiklatDeleteView,
    RiwayatKompetensiView,
    RiwayatKomptensiUpdateView,
    UrutkanRiwayatKompetensiView,
    RiwayatKompetensiDeleteView,
    RiwayatOrganisasiView,
    RiwayatOrganisasiUpdateView,
    UrutkanRiwayatOrganisasiView,
    RiwayatOrganisasiDeleteView,
    RiwayatProfesiView,
    RiwayatSIPProfesiView,
    RiwayatProfesiUpdateView,
    RiwayatSIPProfesiUpdateView,
    UrutkanRiwayatSIPProfesiView,
    RiwayatProfesiDeleteView,
    RiwayatSIPDeleteView,
    RiwayatBekerjaView,
    RiwayatBekerjaUpdateView,
    UrutkanRiwayatBekerjaView,
    RiwayatBekerjaDeleteView,
    RiwayatKeluargaView,
    RiwayatKeluargaUpdateView,
    RiwayatKeluargaDeleteView,
    RiwayatAnggotaKeluargaView,
    RiwayatAnggotaKeluargaUpdateView,
    RiwayatOrangTuaDeleteView,
    RiwayatInovasiView,
    RiwayatInovasiDeleteView,
    UrutkanRiwayatInovasiView,
    RiwayatPenugasanListView,
    RiwayatPenugasanCreateView,
    RiwayatPenugasanUpdateView,
    RiwayatPenugasanDeleteView,
    UrutkanRiwayatPenugasanView,
    GetListRiwayatSDM,
    RiwayatKelengkapan,
    NotFoundPage
)


urlpatterns=[
    path('', RiwayatHomeView.as_view(), name='riwayat_view'),
    path('pendidikan/', RiwayatPendidikanView.as_view(), name='riwayat_pendidikan'),
    path('pendidikan/<int:id>/', RiwayatPendidikanUpdateView.as_view(), name='riwayat_update_pendidikan'),
    path('pendidikan/delete/<int:pk>/', RiwayatPendidikanDeleteView.as_view(), name='riwayat_delete_pendidikan'),
    path('pendidikan/urutkan/<int:pk>/', UrutkanRiwayatPendidikanView.as_view(), name='riwayat_pendidikan_urutkan'),
    path('panggol/', RiwayatPanggolView.as_view(), name='riwayat_panggol'),
    path('panggol/<int:id>/', RiwayatPanggolUpdateView.as_view(), name='riwayat_update_panggol'),
    path('panggol/urutkan/<int:pk>/', UrutkanRiwayatPanggolView.as_view(), name='riwayat_panggol_urutkan'),
    path('panggol/delete/<int:pk>/', RiwayatPanggolDeleteView.as_view(), name='riwayat_delete_panggol'),
    path('pengangkatan/', RiwayatPengangkatanView.as_view(), name='riwayat_pengangkatan'),
    path('pengangkatan/<int:id>/', RiwayatPengangkatanUpdateView.as_view(), name='riwayat_update_pengangkatan'),
    path('pengangkatan/urutkan/<int:pk>/', UrutkanRiwayatPengangkatanView.as_view(), name='riwayat_pengangkatan_urutkan'),
    path('pengangkatan/delete/<int:pk>/', RiwayatPengangkatanDeleteView.as_view(), name='riwayat_delete_pengangkatan'),
    path('jabatan/', RiwayatJabatanView.as_view(), name='riwayat_jabatan'),
    path('jabatan/<int:id>/', RiwayatJabatanUpdateView.as_view(), name='riwayat_update_jabatan'),
    path('jabatan/urutkan/<int:pk>/', UrutkanRiwayatJabatanView.as_view(), name='riwayat_jabatan_urutkan'),
    path('jabatan/delete/<int:pk>/', RiwayatJabatanDeleteView.as_view(), name='riwayat_delete_jabatan'),
    path('penempatan/', RiwayatPenempatanView.as_view(), name='riwayat_penempatan'),
    path('penempatan/<int:id>/', RiwayatPenempatanView.as_view(), name='riwayat_update_penempatan'),
    path('penempatan/urutkan/<int:pk>/', UrutkanRiwayatPenempatanView.as_view(), name='riwayat_penempatan_urutkan'),
    path('penempatan/delete/<int:pk>/', RiwayatPenempatanDeleteView.as_view(), name='riwayat_delete_penempatan'),
    path('penempatan-lainnya/', RiwayatPenempatanInstansiBeforeCreateView.as_view(), name='riwayat_penempatan_lainnya'),
    path('penempatan-lainnya/<int:pk>/', RiwayatPenempatanInstansiBeforUpdateView.as_view(), name='riwayat_update_penempatan_lainnya'),
    path('berkala/', RiwayatGajiBerkalaView.as_view(), name='riwayat_berkala'),
    path('berkala/<int:id>/', RiwayatGajiBerkalaUpdateView.as_view(), name='riwayat_update_berkala'),
    path('berkala/urutkan/<int:pk>/', UrutkanRiwayatGajiBerkalaView.as_view(), name='riwayat_berkala_urutkan'),
    path('berkala/delete/<int:pk>/', RiwayatGajiBerkalaDeleteView.as_view(), name='riwayat_delete_berkala'),
    path('kinerja/', RiwayatKinerjaView.as_view(), name='riwayat_kinerja'),
    path('kinerja/<int:id>/', RiwayatKinerjaUpdateView.as_view(), name='riwayat_update_kinerja'),
    path('kinerja/urutkan/<int:pk>/', UrutkanRiwayatKinerjaView.as_view(), name='riwayat_kinerja_urutkan'),
    path('kinerja/delete/<int:pk>/', RiwayatKinerjaDeleteView.as_view(), name='riwayat_delete_kinerja'),
    path('penghargaan/', RiwayatPenghargaanView.as_view(), name='riwayat_penghargaan'),
    path('penghargaan/<int:id>/', RiwayatPenghargaanUpdateView.as_view(), name='riwayat_update_penghargaan'),
    path('penghargaan/urutkan/<int:pk>/', UrutkanRiwayatPenghargaanView.as_view(), name='riwayat_penghargaan_urutkan'),
    path('penghargaan/delete/<int:pk>/', RiwayatPenghargaanDeleteView.as_view(), name='riwayat_delete_penghargaan'),
    path('hukuman/', RiwayatHukumanView.as_view(), name='riwayat_hukuman'),
    path('hukuman/<int:id>/', RiwayatHukumanUpdateView.as_view(), name='riwayat_update_hukuman'),
    path('hukuman/urutkan/<int:pk>/', UrutkanRiwayatHukumanView.as_view(), name='riwayat_hukuman_urutkan'),
    path('hukuman/delete/<int:pk>/', RiwayatHukumanDeleteView.as_view(), name='riwayat_delete_hukuman'),
    path('cuti/', RiwayatCutiView.as_view(), name='riwayat_cuti'),
    path('cuti/<int:id>/', RiwayatCutiUpdateView.as_view(), name='riwayat_update_cuti'),
    path('cuti/urutkan/<int:pk>/', UrutkanRiwayatCutiView.as_view(), name='riwayat_cuti_urutkan'),
    path('diklat/', RiwayatDiklatListView.as_view(), name='riwayat_diklat'),
    path('diklat/create/', RiwayatDiklatCreateView.as_view(), name='riwayat_diklat_create'),
    path('diklat/<int:pk>/', RiwayatDiklatDetailView.as_view(), name='riwayat_diklat_detail'),
    path('diklat-pegawai/', RiwayatDiklatPegawaiView.as_view(), name='riwayat_diklat_pegawai'),
    path('diklat/<int:id>/', RiwayatDiklatUpdateView.as_view(), name='riwayat_update_diklat'),
    path('diklat/urutkan/<int:pk>/', UrutkanRiwayatDiklatView.as_view(), name='riwayat_diklat_urutkan'),
    path('diklat/delete/<int:pk>/', RiwayatDiklatDeleteView.as_view(), name='riwayat_delete_diklat'),
    path('kompetensi/', RiwayatKompetensiView.as_view(), name='riwayat_kompetensi'),
    path('kompetensi/<int:id>/', RiwayatKomptensiUpdateView.as_view(), name='riwayat_update_kompetensi'),
    path('kompetensi/urutkan/<int:pk>/', UrutkanRiwayatKompetensiView.as_view(), name='riwayat_kompetensi_urutkan'),
    path('kompetensi/delete/<int:pk>/', RiwayatKompetensiDeleteView.as_view(), name='riwayat_delete_kompetensi'),
    path('organisasi/', RiwayatOrganisasiView.as_view(), name='riwayat_organisasi'),
    path('organisasi/<int:id>/', RiwayatOrganisasiUpdateView.as_view(), name='riwayat_update_organisasi'),
    path('organisasi/urutkan/<int:pk>/', UrutkanRiwayatOrganisasiView.as_view(), name='riwayat_organisasi_urutkan'),
    path('organisasi/delete/<int:pk>/', RiwayatOrganisasiDeleteView.as_view(), name='riwayat_delete_organisasi'),
    path('profesi/', RiwayatProfesiView.as_view(), name='riwayat_profesi'),
    path('profesi/<int:id>/', RiwayatProfesiUpdateView.as_view(), name='riwayat_update_profesi'),
    path('profesi/delete/<int:pk>/', RiwayatProfesiDeleteView.as_view(), name='riwayat_delete_profesi'),
    path('sip/<int:id>/', RiwayatSIPProfesiView.as_view(), name='riwayat_sipprofesi'),
    path('sip/update/<int:id_str>/<int:id>/', RiwayatSIPProfesiUpdateView.as_view(), name='riwayat_update_sipprofesi'),
    path('sip/urutkan/<int:pk>/', UrutkanRiwayatSIPProfesiView.as_view(), name='riwayat_sip_urutkan'),
    path('sip/delete/<int:id_str>/<int:pk>/', RiwayatSIPDeleteView.as_view(), name='riwayat_delete_sipprofesi'),
    path('bekerja/', RiwayatBekerjaView.as_view(), name='riwayat_bekerja'),
    path('bekerja/<int:id>/', RiwayatBekerjaUpdateView.as_view(), name='riwayat_update_bekerja'),
    path('bekerja/urutkan/<int:pk>/', UrutkanRiwayatBekerjaView.as_view(), name='riwayat_bekerja_urutkan'),
    path('bekerja/delete/<int:pk>/', RiwayatBekerjaDeleteView.as_view(), name='riwayat_delete_bekerja'),
    path('keluarga/', RiwayatKeluargaView.as_view(), name='riwayat_keluarga'),
    path('keluarga/<int:id>/', RiwayatKeluargaUpdateView.as_view(), name='riwayat_update_keluarga'),
    path('keluarga/delete/<int:pk>/', RiwayatKeluargaDeleteView.as_view(), name='riwayat_delete_keluarga'),
    path('anggota-keluarga/<str:status>/<int:keluarga_id>/', RiwayatAnggotaKeluargaView.as_view(), name='riwayat_anggota_keluarga'),

lapor/urls.py
from django.urls import path
from .views import LaporanView, UpdateLaporanView, SaranView, UpdateSaranView


urlpatterns = [
    path('', LaporanView.as_view(), name='laporan_view'),
    path('<int:id>/', UpdateLaporanView.as_view(), name='laporan_update_view'),
    path('saran/', SaranView.as_view(), name='saran_view'),
    path('saran/<int:id>/', UpdateSaranView.as_view(), name='saran_update_view'),
]

sisdm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('myaccount.urls', 'myaccount_urls'), namespace='myaccount_urls')),
    path('riwayat/', include(('dokumen.urls', 'riwayat_urls'), namespace='riwayat_urls')),
    path('layanan/', include(('layanan.urls', 'layanan_urls'), namespace='layanan_urls')),
    path('struktur/', include(('strukturorg.urls', 'struktur_urls'), namespace='struktur_urls')),
    path('sdm/', include(('jenissdm.urls', 'sdm_urls'), namespace='sdm_urls')),
    path('file/', include(('file_dokumen.urls', 'file_urls'), namespace='file_urls')),
    path('', include(('dashboard.urls', 'dashboard_urls'), namespace='dashboard_urls')),
    path('informasi/', include(('informasi.urls', 'informasi_urls'), namespace='informasi_urls')),
    path('disiplin/', include(('disiplinsdm.urls', 'disiplinsdm_urls'), namespace='disiplinsdm_urls')),
    path('laporan/', include(('lapor.urls', 'laporan_urls'), namespace='laporan_urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dokumen/templates/11_riwayat_diklat/riwayat_diklat_form.html
{% extends '11_riwayat_diklat/riwayat_diklat.html' %}
{% load crispy_forms_tags %}

{% block button %}
    {% if request.user.is_staff and not request.user.is_superuser%}
    <a href="{% url 'riwayat_urls:riwayat_diklat_detail' pk=request.user.id %}" class="btn btn-outline-info">Diklatku</a>
    <a href="{% url 'riwayat_urls:riwayat_diklat' %}" class="btn btn-outline-success">Diklat Pegawai</a>
    {% elif request.user.is_superuser %}
    <a href="{% url 'riwayat_urls:riwayat_diklat' %}" class="btn btn-outline-success">Diklat Pegawai</a>
    {% else %}
    <a href="{% url 'riwayat_urls:riwayat_diklat_detail' pk=request.user.id %}" class="btn btn-outline-info">Diklatku</a>
    {% endif %}
{% endblock %}
{% block child_content %}
    <div class="row">
        <div class="col-md-12">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form | crispy}}
                <input type="submit" value="Simpan" class="btn btn-success">
            </form>
        </div>

    </div>
{% endblock %}

dokumen/templates/11_riwayat_diklat/riwayat_diklat_list_pegawai.html
{% extends '11_riwayat_diklat/riwayat_diklat.html' %}

{% block button %}
{% if request.user.is_superuser %}
<a href="{% url 'riwayat_urls:riwayat_diklat_create' %}" class="btn btn-outline-primary">Tambah Riwayat</a>
{% else %}
<a href="{% url 'riwayat_urls:riwayat_diklat_detail' pk=request.user.id %}" class="btn btn-outline-info">Diklatku</a>
{% endif %}
{% endblock %}

{% block child_content %}
<div class="row">
    <div class="col-md-12">
        <div class="table table-responsive">
            <table class="table" id="data_table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>NIP/NRP</th>
                        <th>Pegawai</th>
                        <th>Tahun Diklat</th>
                        <th>Frekuensi Diklat</th>
                        <th>Jam Diklat</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.profil_user__nip}}</td>
                        <td>{{item.first_name}} {{item.last_name}}</td>
                        <td>{{item.riwayatdiklat__tgl_mulai__year}}</td>
                        <td>{{item.frekuensi_diklat}}</td>
                        <td>{{item.jam_diklat}}</td>
                        <td>
                            <a href="{% url 'riwayat_urls:riwayat_diklat_detail' pk=item.id %}" class="btn btn-primary"><i class="fas fa-info"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#data_table').DataTable({
            dom: 'Blfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf'
            ],
            lengthMenu: [
                [10, 25, 50, -1],
                [10, 25, 50, 'All'],
            ],
        });
    });
</script>

{% endblock %}

                    

dokumen/templates/11_riwayat_diklat/riwayat_diklat_list_perorang.html
{% extends '11_riwayat_diklat/riwayat_diklat.html' %}

{% block button %}
    <a href="{% url 'riwayat_urls:riwayat_diklat_create' %}" class="btn btn-outline-primary">Tambah Riwayat</a>
    {% if request.user.is_staff %}
    <a href="{% url 'riwayat_urls:riwayat_diklat' %}" class="btn btn-outline-info">Diklat Pegawai</a>
    {% endif %}
{% endblock %}

{% block child_content %}
<div class="row">
    <div class="col-md-12">
        <div class="form-group row">
            <label class="col-2">Nama</label>
            <div class="col-10">{{data.full_name}}</div>
        </div>
        <div class="form-group row">
            <label class="col-2">NIP/NRK</label>
            <div class="col-10">{{data.profil_user.nip}}</div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="table table-responsive">
            <table class="table" id="data_table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Jenis Diklat</th>
                        <th>Nama Diklat</th>
                        <th>Penyelenggara</th>
                        <th>No Sertifikat</th>
                        <th>Tanggal Mulai</th>
                        <th>Tanggal Selesai</th>
                        <th>File Sertifikat</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data.riwayatdiklat_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.jenis_diklat}}</td>
                        <td>{{item.nama_diklat}}</td>
                        <td>{{item.penyelenggara}}</td>
                        <td>{{item.no_sertifikat}}</td>
                        <td>{{item.tgl_mulai}}</td>
                        <td>{{item.tgl_selesai}}</td>
                        <td>
                            {% if item.file %}
                            <a href="{{item.file.url}}"><i class="fas fa-file-download"></i></a>
                            {% else %}
                            <i class="fas fa-times" style="font-weight: bold; color:red"></i>
                            {% endif %}
                        </td>
                        <td>
                            <a href="?nip={{item.pegawai.profil_user.nip}}" class="btn btn-primary"><i class="fas fa-user"></i></a>
                            <a href="{% url 'riwayat_urls:riwayat_update_diklat' id=item.id %}" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'riwayat_urls:riwayat_delete_diklat' pk=item.id %}#deletedata" class="btn btn-outline-danger"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
    
{% endblock %}

dokumen/templates/11_riwayat_diklat/riwayat_diklat_master.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
{{title_page}}
{% endblock title_page %}

{% block styles %}
<link rel="stylesheet" href="{% static 'dist/css/riwayat.css' %}">
{% endblock styles %}

{% block navigation %}

{% endblock navigation %}

{% block cardtitle %}

{% endblock cardtitle %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex flex-row justify-content-between">
                    <div class="d-flex flex-row mb-1">
                        {% if update_form or request.user.is_superuser and nip %}
                            <a href="{% url 'riwayat_urls:riwayat_diklat' %}" class="text-dark mr-2"><i class="fas fa-arrow-left ml-2" style="cursor: pointer; font-size:20px;"></i></a>
                        {% endif %}
                        <h5>Data Riwayat Diklat</h5>
                    </div>
                    {% if not update_form %}
                    <div>
                        {% if request.user.is_staff %}
                            <a href="{% url 'riwayat_urls:riwayat_diklat_pegawai' %}" class="btn btn-outline-primary">Diklat Pegawai</a>
                        {% endif %}
                        {% if not request.user.is_superuser %}
                        <a href="{% url 'riwayat_urls:riwayat_diklat_urutkan' pk=dok.id %}" class="btn btn-outline-info">Urutkan Dokumen</a>
                        {% elif nip %}
                        <a href="{% url 'riwayat_urls:riwayat_diklat_urutkan' pk=dok.id %}?nip={{nip}}" class="btn btn-outline-info">Urutkan Dokumen</a>
                        {% endif %}
                        <input type="button" class="btn btn-outline-success" id="add_data" value="Tambah Data">
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                <div class="row" id="form_data" style="display: {{form_view}};">
                    <div class="col-md-12">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form | crispy}}
                            <input type="submit" value="Simpan" class="btn btn-success">
                        </form>
                    </div>
                </div>
                <div class="row" id="list_data" style="display: {{data_view}};">
                    <div class="col-md-12">
                        {% if nip %}
                            {% include '11_riwayat_diklat/riwayat_diklat_perorang.html' %}
                        {% elif request.user.is_superuser  %}
                            {% include '11_riwayat_diklat/riwayat_diklat_list.html' %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- modal delete data -->
    <div id="deletedata" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <a href="#close" title="Close" class="close">&times;</a>
            <h2>Delete Data</h2>
            <p>Apakah benar anda akan menghapus "{{ object }}"?</p>
            <div class="d-flex justify-content-center">
                <form action="#close" method="post">{% csrf_token %}
                    <button class="btn btn-outline-danger" type="submit">Delete</button>
                </form>
                <a href="{% url 'riwayat_urls:riwayat_diklat' %}" class="btn btn-outline-info ml-3">Cancel</a>
            </div>
        </div>
    </div>
{% endblock %}



{% block script %}
<script>
    $(document).ready(function () {
        $('#data_table').DataTable({
            dom: 'Blfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf'
            ],
            lengthMenu: [
                [10, 25, 50, -1],
                [10, 25, 50, 'All'],
            ],
        });
    });
</script>

<script>
    const btn = document.getElementById('add_data');
    
    btn.addEventListener('click', () => {
    const form = document.getElementById('form_data');
    const data = document.getElementById('list_data');

    if (form.style.display === 'none' && data.style.display === 'block') {
        // 👇️ this SHOWS the form
        form.style.display = 'block';
        data.style.display = 'none';
        btn.value="Lihat Data"
      } else {
        // 👇️ this HIDES the form
        form.style.display = 'none';
        data.style.display = 'block';
        btn.value="Tambah Data"
      }
});
</script>
    
{% endblock script %}

dokumen/templates/11_riwayat_diklat/riwayat_diklat_perorang.html
{% extends '11_riwayat_diklat/riwayat_diklat.html' %}

{% block button %}
    
{% endblock %}

{% block child_content %}
<div class="row">
    <div class="col-md-12">
        <div class="form-group row">
            <div class="col-md-3">
                NIP/NRK
            </div>
            <div class="col-md-9">
                {{user.profil_user.nip}}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                Nama
            </div>
            <div class="col-md-9">
                {{user.full_name}}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="table table-responsive">
            <table class="table" id="data_table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Jenis Diklat</th>
                        <th>Nama Diklat</th>
                        <th>Penyelenggara</th>
                        <th>No Sertifikat</th>
                        <th>Tanggal Mulai</th>
                        <th>Tanggal Selesai</th>
                        <th>File Sertifikat</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.jenis_diklat}}</td>
                        <td>{{item.nama_diklat}}</td>
                        <td>{{item.penyelenggara}}</td>
                        <td>{{item.no_sertifikat}}</td>
                        <td>{{item.tgl_mulai}}</td>
                        <td>{{item.tgl_selesai}}</td>
                        <td>
                            {% if item.file %}
                            <a href="{{item.file.url}}"><i class="fas fa-file-download"></i></a>
                            {% else %}
                            <i class="fas fa-times" style="font-weight: bold; color:red"></i>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'riwayat_urls:riwayat_update_diklat' id=item.id %}" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'riwayat_urls:riwayat_delete_diklat' pk=item.id %}#deletedata" class="btn btn-outline-danger"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>        
    </div>
</div>    
{% endblock %}